### PR TITLE
Main+tileexporter fix

### LINKED ISSUE #648: TileExporter requestedPixelSize method gives incorrect results
In the file `qupath-core/src/main/java/qupath/lib/images/writers/TileExporter.java` the definition of the `requestedPixelSize` method has the fraction the wrong way up; it should instead read:

```java
	public TileExporter requestedPixelSize(double pixelSize) {
		this.downsample = pixelSize / server.getPixelCalibration().getAveragedPixelSize().doubleValue();
		return this;
	}
```

Otherwise, if the requested pixel size is 5.0, say, and the average pixel size is 0.25, the downsample value is set to 1/20 instead of the correct 20.

This affects the current GitHub version of QuPath (at commit 3ca92f9026c9c32bcfb28de419673d2beac49c4a).

### LINKED ISSUE #649: A possible (cosmetic?) bug in TileExporter in splitRegionRequests
In `splitRegionRequests`, the working coordinates are in downscaled pixels, and stored in `maxX` and `maxY`.  However, the two nested `for` loops over `x` and `y` have incorrect initialisers: for `y` it is `int y = request.getY()` instead of `int y = (int)(request.getMinY() / downsample)`.  It probably doesn't matter much, though, as presumably `request.getY()` and `request.getMinY()` both return 0 in normal situations.

### LINKED ISSUE #650: In TileExporter, does not correctly loop over t and z values
In the function `getTiledRegionRequests`, there's a nested loop over t and z, but nowhere in the body of the loop are t and z used.  So it would seem that all that would result in the case of an image with nTimepoints > 1 or nZSlices > 1 is multiple identical sets of tiles.  More than that, they would probably just overwrite each other, as in splitRegionRequests, it sets z = request.getZ(), which will presumably always return 0, and likewise for t.  Perhaps the values of z and t should be passed as parameters to splitRegionRequests instead?  That would probably make this work as intended.

### PR DESCRIPTION
**Pull request by juliangilbey**
A clean set of patches this time that fixes #648, fixes #649, fixes #650

### CODE REVIEW

**Comment by petebankhead** [comment]
There shouldn't be any need to pass `z` and `t` as separate parameters to `splitRegionRequests` - rather `fullRequest` can be updated to include these, which would be good to reduce the number of necessary `int` parameters.

Sorry, I don't really have the bandwidth to look at this in detail or handle pull requests in the near future, so this is likely to linger for a while.

**Comment by juliangilbey** [comment]
No rush on my part - just trying to be helpful! :-)

Best wishes, Julian

**Comment by juliangilbey** [comment]
On the thought of not passing the parameters: you could indeed do this by saying:
```java
fullRequest = fullRequest.updateT(t)
fullRequest = fullRequest.updateZ(z)
```
in the loop in `getTiledRegionRequests` and then reinstating these two lines in `splitRegionRequests`:
```java
t = request.getT()
z = request.getZ()
```
So it's a balance between four extra lines of code on the one hand and two extra parameters on the other.

**Comment by petebankhead** [comment]
Finally returning to this - I favour the extra lines of code over the parameters. There are already 4 int parameters, and increasing this to 6 makes it harder to work with I think. The `RegionRequest` *should* be used to incorporate `z` and `t`, and it's really a bug if they are ignored.

I'd also rather add this to the `dev-0.3` branch rather than `main`.

Thanks for looking into all this - If you want to make the changes I can merge them, otherwise one of us can repeat the main bits in a separate pull request later this week.

**Comment by juliangilbey** [comment]
Hi Pete!  I've updated my pull request by basing it on `dev-0.3` and changing the parameter passing as requested.

**Comment by juliangilbey** [comment]
Unfortunately, though, I don't know how to tell GitHub that this patch should be against dev-0.3 rather than against main.  So I'll close this PR and submit a new one.

**Pull request closed without merging**
