### PR TITLE
Fix more typos

### PR DESCRIPTION
**Pull request by camlloyd**
Note I have not addressed the following (here be dragons):

- [ ] `actionInterativeAlignment`
- [ ] `bfUseParallization`
- [ ] `CELL_NULCEI_BOTH`
- [ ] `getAncenstorList`
- [ ] `indexerHierearchy`
- [ ] `initializeMatadata`
- [ ] `matricies`
- [ ] `regionstrationType`

Other inconsistencies:
- [ ] Pyramidize/pyramidalize
- [ ] Descendent/descendant

### CODE REVIEW

**Comment by petebankhead** [comment]
Thanks, I'll look through the ones in the code when I get time, and fix any that are unlikely to anger the dragons too much.

**Comment by petebankhead** [comment]
Most looked pretty innocuous. Only the persistent preference for Bio-Formats has suffered, but I think v0.2.0 may require a new preference key anyway for a clean separation.

Just pyramidize/pyramidalize remains... got a preference?

**Comment by camlloyd** [comment]
I would have to think. I am no expert, but my current understanding is that:

- _to pyramidize_ is to make **x** into a pyramid.
- to _pyramidalize_ is to make **x** pyramidal (pyramid-_shaped_). **x** is not itself a pyramid.

Given the context, there may not be much in it... "Semantics".
Personally, I would go with *pyramidalize*. I could of course be completely mistaken. 

If it's anything to go by, this option also appears more often in the source code.

Or, you could leave it alone for now. It is your call. I wanted to get these polished before v0.2.0, but I know you and Melvin have higher priority tasks at hand*.

*Which is why I wanted to submit these PRs to alleviate you... but they still require your review 🤦

**Comment by petebankhead** [comment]
Sounds good, I feel a slight preference for *pyramidalize* myself... as I guess is reflected in the frequency.

Thanks for submitting these, review was quick :)

v0.2.0 has been a rather intense experience, since almost every part of the software had to be rewritten (after a year away from it), while simultaneously trying to support more and more users navigate the many interrelated and ongoing changes... but I think it was necessary to have a more solid basis for future work. Hopefully, future developments can be a bit less stressful and disruptive for all concerned. It will help not to have to support quite so many misspelled method names :)

**Comment by camlloyd** [comment]
Thank you both for all your efforts. 
It's been a pleasure to follow along and I look forward to seeing what happens next!

**Comment by camlloyd** [comment]
@petebankhead I added another to the list 😅

**Comment by petebankhead** [comment]
Well, it's increasingly clear how much my normal functioning depends upon a spellchecker....

Fixed them now, but unfortunately one instance of `pyramidize` remains - it will turn up on .qpproj files, so changing it without a lot of extra caution would cause compatibility troubles.

**Comment by camlloyd** [comment]
@petebankhead unfortunately `showStarupMesssage` also has one too many `s`

**Comment by petebankhead** [comment]
Fixed! https://github.com/qupath/qupath/pull/498/commits/b797c2cb1d6a974e5f50d01c7bee425a3ca2620e

**Pull request merged**
