### PR TITLE
Replace all uses of Files.exist(path) with path.toFile().exists()

### PR DESCRIPTION
**Pull request by alanocallaghan**
I did this with `egrep -rl "Files\.exists\(\w+\)" | xargs sed -E -i 's/Files\.exists\((\w+)\)/\1.toFile().exists()/g'` so there's a non-zero chance I missed some usages (anything with a method or field access in the something of `Files.exists(something)` will be missed) and a small chance I broke something, but I didn't want the regex to get too complex.

Based on apparently slow performance, see
https://rules.sonarsource.com/java/RSPEC-3725/

https://github.com/qupath/qupath-extension-wsinfer/pull/30
https://github.com/qupath/qupath/issues/1154#issuecomment-1327044045

### CODE REVIEW

**Comment by petebankhead** [comment]
Nice regex :)

Makes me a bit nervous, since I'm not aware of anything currently being broken. Definitely worth considering `File.exists()` instead of `Files.exists(path)` when it's called a lot in a loop (and I guess anything *could* be called a lot in a loop by other code).

Any way to quickly benchmark the difference?

I guess we also want to know if one method is substantially faster or slower for checking files over a network, as well as local files.

(Conceivably we might also add our own method, e.g. `GeneralTools.checkFileExists()` or something and then use our preferred implementation in one place... but not sure if that's just adding awkwardness.)

**Comment by alanocallaghan** [comment]
I'll benchmark Files.exists(file) vs file.exists() locally later, though it'll probably be worth checking performance on a samba mount as well as nfs/sshfs

**Comment by alanocallaghan** [comment]
So on linux on 3000 files (random content, random size), `Files.exist(path)` takes 0.035 seconds while `file.exists()` takes 0.047 seconds. Pretty weird stuff, it may be a Windows issue

**Comment by petebankhead** [comment]
I got curious too and tried an extremely rough and messy benchmarking as well - `Files.exist(path)` was quicker for me too (although I checked the same files multiple times, and lots of files that didn't exist).

Maybe a Windows, Java version, or network issue...

**Comment by petebankhead** [comment]
I was seeing a bigger difference (`Files.exist(path)` taking about 1/3 the time)

**Comment by alanocallaghan** [comment]
The linked issue seems very extreme, unless you are checking almost the whole HD then 260 seconds is unreasonable, and if switching to file.exists() solves that then I think it's worth taking a much smaller hit on other platforms

**Comment by petebankhead** [comment]
From the other thread I'm not sure if it does solve the issue though :/ 

There have been obscure problems in the past through the use of `File` instead of `Path`, so nothing seems straightforward: https://github.com/Bayer-Group/paquo/issues/65#issuecomment-1312398115

**Comment by alanocallaghan** [comment]
On windows:

```
INFO: Same: true
INFO: Paths 	37.279 s
Files 	17.887 s
Total duration	55.166 s
Average per checkpoint: 27.583 s
```

**Comment by alanocallaghan** [comment]
Slightly updated script showing there is indeed some badness going on (note the counts don't match!)

```groovy
import groovy.transform.CompileStatic
import qupath.lib.common.Timeit

import java.nio.file.Files
import java.nio.file.Path

List<File> files = new File(System.getProperty("user.home")).listFiles() as List

for (int i = 0; i < 10; i++)
    files.add(new File(Math.random() as String))

List<Path> paths = files.collect(f -> f.toPath()) as List

int nIterations = 1000
println("Same: " + (countFilesExist(files) == countPathsExist(paths)))
println("Count files: " + countFilesExist(files))
println("Count paths: " + countPathsExist(paths))


println new Timeit()
        .checkpointAndRun("Paths ", () -> countPathsExist(paths, nIterations))
        .checkpointAndRun("Files ", () -> countFilesExist(files, nIterations))
        .stop()
        .summarizeCheckpoints()


@CompileStatic
int countFilesExist(List<File> files, int iterations=1) {
    int count = 0;
    for (int i = 0; i < iterations; i++) {
        for (def f : files) {
            if (f.exists())
                count++;
        }
    }
    return count;
}

@CompileStatic
int countPathsExist(List<Path> files, int iterations=1) {
    int count = 0;
    for (int i = 0; i < iterations; i++) {
        for (def f : files) {
            if (Files.exists(f))
                count++;
        }
    }
    return count;
}
```

Windows:
```
INFO: Same: false
INFO: Count files: 51
INFO: Count paths: 38
INFO: Paths 	4.273 s
Files 	1.838 s
Total duration	6.111 s
Average per checkpoint: 3.055 s
```

**Comment by petebankhead** [comment]
Does it persist if you switch the order that you compare `Files` and `File`?

Also... why do they not match?!?

**Comment by alanocallaghan** [comment]
Ubuntu/PopOS results, pretty much what I expected, more files less time, no inconsistency:

```
INFO: Starting script at Thu Aug 24 14:47:27 BST 2023
INFO: Same: true
INFO: Count files: 208
INFO: Count paths: 208
INFO: Paths 	598 ms
Files 	319 ms
Total duration	917 ms
Average per checkpoint: 458 ms
INFO: Total run time: 2.68 seconds
```

> Also... why do they not match?!?

The unholy combination that is Windows and Java, I guess

**Comment by alanocallaghan** [comment]
The files that mismatch are things like `C:\Users\alano\Application Data`, which doesn't seem to exist, at least when I paste it into explorer I get `[directory] is not accessible. Access is denied`, and they're not visible when viewing the parent dir in explorer or cmd. Somewhat bizarre behaviour, can chalk it up to Windows I think

**Comment by petebankhead** [comment]
Hmmm, in that case though we might prefer `paths` for not creating the impression that they exist?

I have the impression there isn't a clear winner here, and so I tend towards prefering `Files.exist` for its modern nature (and I see the implementation is at least partly different in an upcoming JDK) - although that could change it one turns out to have exceptionally horribly performance, e.g. for a network share.

**Pull request closed without merging**
