### PR TITLE
Fixes: columnImage is null

### PR DESCRIPTION
**Pull request by ajay1685**
This seems to address the ```"columnImage" is null``` error mentioned in #1083 when loading the qptma file in the TMA Data Viewer.

### CODE REVIEW

**Comment by petebankhead** [comment]
Thanks! Not certain because I haven't run it, but looks like it should be
```java
if (hasImages) {
    columnImage.setPrefWidth(n.doubleValue());
    table.refresh();
}
```
since likely no need to call refresh unless there are images. Does that work?

**Comment by ajay1685** [comment]
I tested your suggestion and included the fix. Now both column ```columnImage``` & ```columnOverlay``` sizes are in sync. Adjusting one also adjusts the other proportionally. I believe this is the correct behavior.

**Comment by ajay1685** [comment]
The commit [f37dcfc](https://github.com/qupath/qupath/pull/1096/commits/f37dcfc63cc65a43b8a0eba76e7b7db86c3d75bc) assumes both the ```columnImage``` & ```columnOverlay``` are available and works well when it is true. Table does not seem to refresh when only one of them is available. 
Hence the table may need to be refreshed outside the ```if``` statement. Does this mean that the table may refresh twice when both column are available ? 
This one is trickier that I had initially thought.
 
```java
		// Add columns to show images, if we have them
		if (hasImages || hasOverlay) {
			TreeTableColumn<TMAEntry, TMAEntry> columnImage = hasImages ? new TreeTableColumn<>("Thumbnail") : null;
			TreeTableColumn<TMAEntry, TMAEntry> columnOverlay = hasOverlay ? new TreeTableColumn<>("Overlay") : null;

			if (hasImages) {
				columnImage.setCellValueFactory(new Callback<CellDataFeatures<TMAEntry, TMAEntry>, ObservableValue<TMAEntry>>() {
					@Override
					public ObservableValue<TMAEntry> call(CellDataFeatures<TMAEntry, TMAEntry> p) {
						return p.getValue().valueProperty();
					}
				});
				columnImage.setCellFactory(c -> new ImageTableCell(imageCache, false));
				columnImage.maxWidthProperty().bind(maxSmallWidth);
				columnImage.widthProperty().addListener((v, o, n) -> {
					if (n.doubleValue() == columnImage.getPrefWidth())
						return;
					if (hasOverlay)
						columnOverlay.setPrefWidth(n.doubleValue());
					table.refresh();
				});
				columns.add(columnImage);
			}

			if (hasOverlay) {
				columnOverlay.setCellValueFactory(new Callback<CellDataFeatures<TMAEntry, TMAEntry>, ObservableValue<TMAEntry>>() {
					@Override
					public ObservableValue<TMAEntry> call(CellDataFeatures<TMAEntry, TMAEntry> p) {
						return p.getValue().valueProperty();
					}
				});
				columnOverlay.setCellFactory(c -> new ImageTableCell(imageCache, true));
				columnOverlay.maxWidthProperty().bind(maxSmallWidth);
				columnOverlay.widthProperty().addListener((v, o, n) -> {
					if (n.doubleValue() == columnOverlay.getPrefWidth())
						return;
					if (hasImages)
						columnImage.setPrefWidth(n.doubleValue());
					table.refresh();
				});
				columns.add(columnOverlay);
			}
		}
```

This might be better for now! Since it works in both cases:
1. If both ```columnImage``` and ```columnOverlay``` are available.
2. When one of the ```columnImage``` or ```columnOverlay``` is not available.

I discovered this because when TMA Data is exported for the multichannel image (non-RGB) it is exported as TIF. The TMA viewer only seems to load the image if it is saved as .jpg. For the overlay it load either .jpg or .png.

Here is TMA Data exporter code that exports the images:
https://github.com/petebankhead/qupath/blob/fca7fa5fd9efd815f4c317705fbe2a0f9c39270f/qupath-gui-fx/src/main/java/qupath/lib/gui/tma/TMADataIO.java#L107
```jave
	String coreExt = imageData.getServer().isRGB() ? ".jpg" : ".tif";
```

and Here is TMA Data Viewer code that loads the images:
https://github.com/petebankhead/qupath/blob/fca7fa5fd9efd815f4c317705fbe2a0f9c39270f/qupath-gui-fx/src/main/java/qupath/lib/gui/tma/TMASummaryViewer.java#L1714
```
	File fileImage = new File(dirData, name + ".jpg");
```

**Comment by petebankhead** [comment]
Refreshing slightly more than necessary is probably ok, it's only a problem if you notice it slowing things down. Certainly better than missing a necessary `refresh()` call :)

There's no .tif support because then that brings in channel colors/brightness & contrast and so on, so I guess that would require a more core change to export with those settings. But that gets even more awkward if the visualization settings might not be available if calling the export by batch processing...

**Comment by petebankhead** [comment]
Incidentally, if you're enjoying it and want to tackle the sluggishness you could try setting the cell height to be fixed - although it's tricky because it will depend upon the image size. So you'll need to bring to some other property, and make sure it never gets too small (or fails horribly if images are missing).

I introduced that recently in the regular measurement tables and it improved performance quite a bit. The code I used is at https://github.com/qupath/qupath/blob/main/qupath-gui-fx/src/main/java/qupath/lib/gui/commands/SummaryMeasurementTableCommand.java#L210

See here for more info: https://openjfx.io/javadoc/12/javafx.controls/javafx/scene/control/TableView.html#fixedCellSizeProperty()

(Not necessary though - just if you're curious!)

**Comment by ajay1685** [comment]
I think this will do. let's not make this pull request any messier than it already is. Any new issues will need to be a separate issue with it's own PR :)

**Pull request merged**
