### PR TITLE
Support system light/dark mode

### PR DESCRIPTION
**Pull request by petebankhead**
Also use the system style by default.

This seems to be working for me on macOS - @alanocallaghan and @finglis could you let me know if it works ok on Linux & Windows too please?

style_light-1

style_dark-1

### CODE REVIEW

**Comment by alanocallaghan** [comment]
Works great on my Linux box, an Ubuntu 22.04 derivative with GNOME desktop environment:

```
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

Would probably be worthwhile checking a KDE plasma version, will look into that quickly

**Comment by finglis** [comment]
Windows is responding as expected

**Comment by petebankhead** [comment]
Ah, that's a bit of a shame... but thanks for testing - there might be some other [platform preferences](https://openjfx.io/javadoc/23/javafx.graphics/javafx/application/Platform.Preferences.html) that help, although I'd be tempted to just leave is a bug that may magically get fixed by dependency updates. We still have the option to choose light or dark explicitly, so as long as that still works no one should be stuck.

**Comment by alanocallaghan** [comment]
In fairness, I tested on Plasma and it seems like `Platform.getPreferences().getColorScheme()` is indeed returning light when dark and dark when light, so there's not a whole lot we can do to handle that

**Pull request merged**
