### PR TITLE
Fix typo in DragDrop listener and move strings to resourceBundle

### PR DESCRIPTION
**Pull request by alanocallaghan**
The typo was "Please drag the file only a specific viewer to open", but I figured if I was fixing it I may as well plop the GUI strings into the resources as well.

Obviously not even close to urgent

### CODE REVIEW

**Comment by alanocallaghan** [comment]
While I'm at it, the URL drag and drop produces an uncaught exception when you drag a URL on and off QuPath without dropping: 

```
java.lang.IllegalStateException: setDropCompleted can be called only from DRAG_DROPPED handler
	at javafx.scene.input.DragEvent.setDropCompleted(DragEvent.java:736)
	at qupath.lib.gui.viewer.DragDropImportListener.handle(DragDropImportListener.java:199)
	at qupath.lib.gui.viewer.DragDropImportListener.handle(DragDropImportListener.java:78)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:3144)
	at javafx.scene.Scene$DnDGesture.processTargetEnterOver(Scene.java:3316)
	at javafx.scene.Scene$DropTargetListener.dragEnter(Scene.java:3024)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragEnter$0(GlassSceneDnDEventHandler.java:83)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragEnter(GlassSceneDnDEventHandler.java:77)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragEnter$9(GlassViewEventHandler.java:733)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragEnter(GlassViewEventHandler.java:732)
	at com.sun.glass.ui.View.handleDragEnter(View.java:684)
	at com.sun.glass.ui.View.notifyDragEnter(View.java:1020)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
13:36:13.428 [JavaFX Application Thread] [ERROR] q.l.g.QuPathUncaughtExceptionHandler - setDropCompleted can be called only from DRAG_DROPPED handler (see full stack trace above, or use 'debug' log level)
13:36:13.788 [JavaFX Application Thread] [ERROR] q.l.g.QuPathUncaughtExceptionHandler - setDropCompleted can be called only from DRAG_DROPPED handler (see full stack trace above, or use 'debug' log level)
13:36:14.052 [JavaFX Application Thread] [ERROR] q.l.g.QuPathUncaughtExceptionHandler - setDropCompleted can be called only from DRAG_DROPPED handler (see full stack trace above, or use 'debug' log level)
```

This doesn't happen with files or lists.

**Comment by petebankhead** [comment]
Thanks, I made a small change to reinstate the imports that had been converted to starred imports* & fixed a few of my old formatting/doc issues

I can't replicate the bug on my Mac - if I drag a URL from chrome, the dragboard contains both a URL and a String - but good if it solves the problem somewhere.

*-I've consistently avoided them & convinced my IntelliJ to stop doing it automatically - can discuss later if we want to change that policy.

**Comment by alanocallaghan** [comment]
> I can't replicate the bug on my Mac - if I drag a URL from chrome, the dragboard contains both a URL and a String - but good if it solves the problem somewhere.

Yeah I suspect it's a Linux issue, either way I think trying to handle Strings as URLs is about the best we can do, as long as it shows the right kind of error.

> *-I've consistently avoided [starred imports] & convinced my IntelliJ to stop doing it automatically - can discuss later if we want to change that policy.

I don't pay any heed to imports; they're automatically hidden for me. The only strong argument I've been exposed to on the topic was that having a) a license and b) every imported class/static method right at the top of the file means that every file you open, you need to page down a couple of times before reading any code. If there was a risk of ambiguity I might be more concerned, but I think when there's a collision Java forces you to use a fully qualified name?

Anyways I think the license and imports are auto-hidden for me, so this doesn't really matter

**Comment by petebankhead** [comment]
> I think when there's a collision Java forces you to use a fully qualified name

It does, but I think they look ugly and weird in code.

I tend to prefer the overview of what the class really uses, rather than 'a class here, a class there, some between 0 and absolutely everything from package X...'.

I figure that, even with starred imports, there will be a need to page down anyway.

**Pull request merged**
