### PR TITLE
Added maven plugin

### PR DESCRIPTION
**Pull request by arvgord**
For compatibility with maven-built extensions.

### CODE REVIEW

**Comment by petebankhead** [comment]
Can you elaborate on what this does and why it would help to include in the main repo?

**Comment by arvgord** [comment]
Because I have built-in dependencies in pom.xml(in my extension for QuPath) from qupath-gui-fx. For resolving these dependencies I need to install qupath libraries to local maven repository. But last QuPath version built on gradle and I can't do this without maven plugin in gradle.built.

**Comment by arvgord** [comment]
It will be useful for other developers who maintain maven-based extensions for QuPath.

**Comment by petebankhead** [comment]
I'm not sure that there are (many/any?) other developers maintaining maven-based extensions for QuPath, and gradle is the recommended approach. I'm reluctant to add something like this to the main build script when it isn't actually needed to build QuPath itself, and many people (including me) may prefer not to install the jars to their local maven repository.

In any case, I understand there are other ways to install the jars locally, e.g. https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

Currently I am refactoring and aiming to reduce as much of complexity as possible to make the software more maintainable. It may be worth revisiting the use of Maven when this is complete.

**Pull request closed without merging**
