### PR TITLE
Add additional badges to Readme.md

### PR DESCRIPTION
**Pull request by ajay1685**
Add badge for number of downloads (all releases), downloads for latest release and DOI link.
image

### CODE REVIEW

**Comment by petebankhead** [comment]
Looks good to have this info visible. Where do you find the codes for this?

One weird thing: there's a reference to 10.1007/978-3-319-76207-4_15 that doesn't look like it should be there.

**Comment by ajay1685** [comment]
I found a few example of badges here:
https://github.com/Naereen/badges

I didn't realize Zenodo offers more than just a badge, here are the instructions to setup Zenodo for archival. 
https://guides.github.com/activities/citable-code/

I removed Zenodo reference from this pull request.

**Comment by ajay1685** [comment]
Closing this in favor of 68aab01

**Comment by petebankhead** [comment]
Cheers, hope you don't mind! Thanks for flagging these, added the badges with some other changes needed to update the ReadMe in a single commit.

**Comment by Svidro** [comment]
So... successful badge-ering?

...

I will see myself out.

**Pull request closed without merging**
