### PR TITLE
Update jpackage.yml for mac aarch64

### PR DESCRIPTION
**Pull request by petebankhead**
See https://github.com/qupath/qupath/issues/1458

### CODE REVIEW

**Comment by alanocallaghan** [comment]
Is it worth revisiting the idea of a draft release pipeline using actions? Manually triggered

**Comment by petebankhead** [comment]
Sounds good, as long as it doesn't enforce any tag until we *actually* release.

Also, if you want to take it on... I think this PR fails because the two mac builds become 'pkg' and only one survives.

**Comment by alanocallaghan** [comment]
Question: why do we upload javadocs for each? I'd have thought these would be the same across platforms/architectures?

**Comment by petebankhead** [comment]
Closed in favor of https://github.com/qupath/qupath/pull/1464

**Pull request closed without merging**
