### PR TITLE
Make AbstractTileableImageServer.readRegion return an empty tile when AbstractTileableImageServer.readTile returns an empty tile

### PR DESCRIPTION
**Pull request by Rylern**
When reading an **empty** region (I'm not sure of the term, see the first screenshot of #1443) from a [SparseImageServer](https://github.com/qupath/qupath/blob/main/qupath-core/src/main/java/qupath/lib/images/servers/SparseImageServer.java):
* the [SparseImageServer.readTile()](https://github.com/qupath/qupath/blob/13bdeed047b4d05f35f47308b36b48c0f2bb3a24/qupath-core/src/main/java/qupath/lib/images/servers/SparseImageServer.java#L221) function returns an empty `BufferedImage`.
* but the [AbstractTileableImageServer.readRegion()](https://github.com/qupath/qupath/blob/13bdeed047b4d05f35f47308b36b48c0f2bb3a24/qupath-core/src/main/java/qupath/lib/images/servers/AbstractTileableImageServer.java#L266) (which is extended by SparseImageServer) function returns `null`.

This means that calling `SparseImageServer.readRegion()` on empty regions will return `null`, which can triggers errors (see #1443).

This PR makes `AbstractTileableImageServer.readRegion()` return an empty tile (instead of `null`) when `AbstractTileableImageServer.readTile()` returns an empty tile. This should fix the first issue of #1443.

### CODE REVIEW

**Comment by petebankhead** [comment]
I think this is a good & elegant way to fix the problem. I haven't merged it yet as I'm trying to think if it could have any other implications that mean we should target v0.6.0 rather than v0.5.1.

Were you able to reproduce the original error? I've tried creating some training images with empty regions, but haven't managed to cause the problem yet.

**Comment by Rylern** [comment]
Yes, in a project, start from LuCa-7color_[17572,60173]_3x3component_data.tif, define two annotations with the Region class like this:
Screenshot from 2024-02-29 15-14-35

Then Classify, Training Images, Create Training images, default parameters, and it creates this image:
image

Then this script throws the error:

```groovy
setImageType('FLUORESCENCE');
selectAnnotations();
runPlugin('qupath.imagej.detect.cells.WatershedCellDetection', '{"detectionImage":"DAPI","requestedPixelSizeMicrons":0.1,"backgroundRadiusMicrons":4.0,"backgroundByReconstruction":true,"medianRadiusMicrons":1.0,"sigmaMicrons":2.5,"minAreaMicrons":11.0,"maxAreaMicrons":400.0,"threshold":1000.0,"watershedPostProcess":true,"cellExpansionMicrons":5.0,"includeNuclei":true,"smoothBoundaries":true,"makeMeasurements":true}')
```

**Comment by petebankhead** [comment]
Great, thanks - can replicate it now. I was trying something similar but the key difference was that I was using an RGB image, and that seems to always work.

Well, the current `ImageServer` interface seems to have evolved into a bit of a mess. A note in the javadocs seems to suggest we shouldn't return `null` anyway: https://github.com/qupath/qupath/blob/474c08c13381c87969b7874ea3e5b4850757c7ba/qupath-core/src/main/java/qupath/lib/images/servers/ImageServer.java#L202

But another note suggests that `isEmptyRegion` can be used to determine when `readBufferedImage` (now `readRegion`) would return `null`:
https://github.com/qupath/qupath/blob/474c08c13381c87969b7874ea3e5b4850757c7ba/qupath-core/src/main/java/qupath/lib/images/servers/ImageServer.java#L314

So... definitely need to fix this for v0.6.0, maybe should already tackle it in v0.5.1.

**Comment by petebankhead** [comment]
I've updated one of my old incorrect javadocs - assuming it still builds fine I think this is good to merge, thanks!

**Pull request merged**
